{
  "openapi": "3.1.0",
  "x-stoplight": {
    "id": "iarihuyxupl6h"
  },
  "info": {
    "title": "Partner to PickUpPoint",
    "version": "1.0",
    "description": "This document contains the technical information about Woop APIs for pick-up point. For any questions or clarifications, please contact the internal technical team.\n\nTo use Woop APIs, you must use the confidential access codes.\n\nThe version currently available in the documentation is <b>Version 1.0.0</b>",
    "summary": ""
  },
  "servers": [
    {
      "description": "Production URL",
      "url": "pickup-points.gcp.last-mile.fr"
    },
    {
      "description": "Pre-production URL",
      "url": "pickup-points.preprod.gcp.last-mile.fr"
    },
    {
      "description": "Staging URL",
      "url": "pickup-points.recette.gcp.last-mile.fr"
    }
  ],
  "paths": {
    "/bookings/{bookingId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "bookingId",
          "in": "path",
          "description": "booking id",
          "required": true
        }
      ],
      "get": {
        "summary": "Get Booking ID",
        "tags": [
          "Booking"
        ],
        "responses": {
          "200": {
            "description": "User Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "booking": {
                      "type": "object",
                      "x-stoplight": {
                        "id": "74zr8jf1zx5zo"
                      },
                      "properties": {
                        "pickupPointId": {
                          "$ref": "../models/PickUpPoint/pickUpPointId.json",
                          "x-stoplight": {
                            "id": "iuz1pdxlmhqrj"
                          }
                        },
                        "interval": {
                          "$ref": "../models/Common/interval.json",
                          "x-stoplight": {
                            "id": "hhb0sgy6pk1e5"
                          }
                        },
                        "categoryId": {
                          "$ref": "../models/PickUpPoint/boxCategoryId.json",
                          "x-stoplight": {
                            "id": "eojcw2nu8jgbg"
                          }
                        },
                        "categoryCode": {
                          "$ref": "../models/PickUpPoint/boxCategoryCode.json",
                          "x-stoplight": {
                            "id": "e83a901nm4ank"
                          }
                        },
                        "statuses": {
                          "type": "array",
                          "x-stoplight": {
                            "id": "y04y2p6aun0ks"
                          },
                          "items": {
                            "x-stoplight": {
                              "id": "ibql8nxsco6fv"
                            },
                            "type": "object",
                            "properties": {
                              "status": {
                                "type": "string",
                                "x-stoplight": {
                                  "id": "5emtwqdra8w6b"
                                }
                              },
                              "subStatus": {
                                "type": "string",
                                "x-stoplight": {
                                  "id": "l8rxzsaagtc2f"
                                }
                              },
                              "date": {
                                "type": "string",
                                "x-stoplight": {
                                  "id": "00rr7w5zqj3yg"
                                },
                                "format": "date-time"
                              },
                              "comment": {
                                "type": "string",
                                "x-stoplight": {
                                  "id": "1r5teirkpu0of"
                                }
                              }
                            },
                            "required": [
                              "status",
                              "date"
                            ]
                          }
                        }
                      },
                      "required": [
                        "pickupPointId",
                        "interval",
                        "statuses"
                      ]
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "statuses": [
                        {
                          "status": "string",
                          "subStatus": "string",
                          "date": "2019-08-24T14:15:22Z",
                          "comment": "string"
                        }
                      ],
                      "interval": {
                        "start": "2019-12-04T12:30:00+0000",
                        "end": "2019-12-04T14:30:00+0000"
                      },
                      "categoryId": "BoxCategory_001",
                      "categoryCode": "S"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - You are not allowed to access this item."
          },
          "404": {
            "description": "Bad Request - Missing and/or incorrect items in the body",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/badRequest.json"
                }
              }
            }
          }
        },
        "operationId": "get-booking-Id",
        "description": "Retrieve the information of the external booking with the matching booking ID.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "../models/PickUpPoint/bookingId.json"
              },
              "examples": {
                "Example 1": {
                  "value": "Booking_001"
                }
              }
            }
          }
        },
        "x-stoplight": {
          "id": "5h3zc0sqfga4x"
        }
      },
      "delete": {
        "summary": "DELETE Booking ID",
        "tags": [
          "Booking"
        ],
        "responses": {
          "204": {
            "description": "Successfully cancelled booking"
          },
          "401": {
            "description": "Unauthorized - The booking cannot be cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - the booking has already been cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found - the booking does not exist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                }
              }
            }
          }
        },
        "operationId": "delete-bookingId",
        "x-stoplight": {
          "id": "6bcmulmnurwds"
        },
        "description": " API to delete an external booking."
      },
      "patch": {
        "summary": "PATCH Booking ID",
        "tags": [
          "Booking"
        ],
        "responses": {
          "204": {
            "description": "the booking has been modified",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": [
                    "bookingId",
                    "loadingIdendification",
                    "unloadingIdentification"
                  ],
                  "properties": {
                    "bookingId": {
                      "type": "string",
                      "x-stoplight": {
                        "id": "4d2avanwxw05c"
                      }
                    },
                    "loadingIdendification": {
                      "$ref": "../models/PickUpPoint/identification.json",
                      "x-stoplight": {
                        "id": "ukdwjx24ozkri"
                      }
                    },
                    "unloadingIdentification": {
                      "$ref": "../models/PickUpPoint/identification.json",
                      "x-stoplight": {
                        "id": "5crt6brymr4a2"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                }
              }
            }
          },
          "404": {
            "description": "bookingId Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                }
              }
            }
          }
        },
        "operationId": "patch-bookingId",
        "x-stoplight": {
          "id": "p41umy52ur9jd"
        },
        "description": "Patch the necessary fields for the API to modify an external booking.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "boxCategory": {
                    "$ref": "../models/PickUpPoint/boxCategory.json",
                    "x-stoplight": {
                      "id": "laewmbcqi2kj7"
                    }
                  },
                  "interval": {
                    "$ref": "../models/Common/interval.json",
                    "x-stoplight": {
                      "id": "jifxoa44coo2m"
                    }
                  },
                  "packages": {
                    "$ref": "../models/Package/package.json",
                    "x-stoplight": {
                      "id": "unus76am24mjb"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/bookings": {
      "post": {
        "summary": "POST Bookings",
        "operationId": "post-bookings",
        "responses": {
          "200": {
            "description": "the booking has been registered",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": [
                    "booking"
                  ],
                  "properties": {
                    "booking": {
                      "type": "object",
                      "x-stoplight": {
                        "id": "t36vnq0ldjcu0"
                      },
                      "required": [
                        "externalId",
                        "loadingIdentification",
                        "unloadingIdentification"
                      ],
                      "properties": {
                        "externalId": {
                          "type": "string",
                          "x-stoplight": {
                            "id": "atr52wo1jzozb"
                          },
                          "description": "external booking id"
                        },
                        "loadingIdentification": {
                          "$ref": "../models/PickUpPoint/identification.json",
                          "x-stoplight": {
                            "id": "jw1xxpftdrwj8"
                          }
                        },
                        "unloadingIdentification": {
                          "$ref": "../models/PickUpPoint/identification.json",
                          "x-stoplight": {
                            "id": "4eq9ag5t1lm2t"
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "bookingId": "Booking_001",
                      "loadingIdentification": {
                        "barcode": {
                          "value": "54fd56g4f5gfd456sd",
                          "type": "barcode",
                          "format": "128"
                        },
                        "pinCode": "123456"
                      },
                      "unloadingIdentification": {
                        "barcode": {
                          "value": "54fd56g4f5gfd456sd",
                          "type": "barcode",
                          "format": "128"
                        },
                        "pinCode": "123456"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/badRequest.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          },
          "409": {
            "description": "Conflict"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "pickupPointId",
                  "operatorCode",
                  "interval",
                  "packages"
                ],
                "properties": {
                  "pickupPointId": {
                    "$ref": "../models/PickUpPoint/pickUpPointId.json",
                    "x-stoplight": {
                      "id": "nkmclhbtx7q8v"
                    }
                  },
                  "operatorCode": {
                    "$ref": "../models/PickUpPoint/networkOperatorCode.json",
                    "x-stoplight": {
                      "id": "x9mw2333ram68"
                    }
                  },
                  "interval": {
                    "$ref": "../models/Common/interval.json",
                    "x-stoplight": {
                      "id": "h04rmoahd417y"
                    }
                  },
                  "packages": {
                    "$ref": "../models/Package/packageBooking.json",
                    "x-stoplight": {
                      "id": "fjks0mcuqfyj5"
                    }
                  },
                  "boxCategory": {
                    "$ref": "../models/PickUpPoint/boxCategoryBooking.json",
                    "x-stoplight": {
                      "id": "dgt0v4e3c4bs8"
                    }
                  },
                  "loadingIdentification": {
                    "$ref": "../models/PickUpPoint/identification.json",
                    "x-stoplight": {
                      "id": "6k73knzwtb6m2"
                    }
                  }
                }
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "pickUpPointId": "PickUpPoint_001",
                    "operator": "NetworkOperator_001",
                    "interval": {
                      "start": "2019-12-04T12:30:00+0000",
                      "end": "2019-12-04T14:30:00+0000"
                    },
                    "packages": {
                      "references": [
                        {
                          "reference": "Package_Reference_001",
                          "barcode": {
                            "value": "54fd56g4f5gfd456sd",
                            "type": "barcode",
                            "format": "128"
                          }
                        }
                      ],
                      "length": {
                        "value": 10,
                        "unit": "cm"
                      },
                      "width": {
                        "value": 10,
                        "unit": "cm"
                      },
                      "height": {
                        "value": 10,
                        "unit": "cm"
                      },
                      "weight": {
                        "value": 5,
                        "unit": "kg"
                      },
                      "products": [
                        {
                          "type": "TYPOLOGY_GENERIC",
                          "ean": "Ean_001",
                          "cug": "Cug_001",
                          "label": "Product_Label",
                          "quantity": 1
                        }
                      ],
                      "quantity": 1,
                      "attributes": {
                        "footprint": {
                          "value": 10,
                          "unit": "m2"
                        }
                      },
                      "type": "PACKAGE"
                    },
                    "boxCategory": {
                      "id": "BoxCategory_001",
                      "code": "S",
                      "accessibility": "UPPER"
                    }
                  }
                }
              }
            }
          },
          "description": "Post the necessary fields for the API to create a new booking."
        },
        "description": "Create a new external booking.",
        "x-stoplight": {
          "id": "guguwwf69z0pt"
        },
        "tags": [
          "Booking"
        ]
      },
      "parameters": [],
      "get": {
        "summary": "GET Booking (all)",
        "operationId": "get-pickupPoints-bookings",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "Example 1": {
                      "bookings": [
                        {
                          "id": "string",
                          "status": "string",
                          "subStatus": "string",
                          "date": "2019-08-24T14:15:22Z",
                          "comment": "string",
                          "pickUpPointId": "PickUpPoint_001"
                        }
                      ]
                    }
                  },
                  "properties": {
                    "bookings": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "status": {
                            "type": "string"
                          },
                          "subStatus": {
                            "type": "string"
                          },
                          "date": {
                            "type": "string"
                          },
                          "comment": {
                            "type": "string"
                          },
                          "pickUpPointId": {
                            "$ref": "../models/PickUpPoint/pickUpPointId.json"
                          }
                        },
                        "required": [
                          "id",
                          "status",
                          "pickUpPointId"
                        ]
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "bookings": [
                        {
                          "id": "string",
                          "status": "string",
                          "subStatus": "string",
                          "date": "string",
                          "comment": "string",
                          "pickUpPointId": "string"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "pickupPointId",
            "description": "pick up point Id"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "status",
            "description": "booking status"
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "subStatus",
            "description": "booking substatus"
          }
        ],
        "x-stoplight": {
          "id": "b4kaea8ml1wxr"
        },
        "description": "Retrieve the information from all external bookings",
        "tags": [
          "Booking"
        ]
      }
    },
    "/pickupPoints": {
      "post": {
        "summary": "Search pickup-Points",
        "tags": [
          "Pickup-points"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/postPickupPoints"
          },
          "400": {
            "description": "Missing and/or incorrect items in the body",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "statusCode": 0,
                      "error": "string",
                      "message": "string",
                      "reasons": [
                        "STORE_NOT_FOUND"
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "You are not allowed to access this item.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../models/Common/errorCode.json"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "statusCode": 0,
                      "error": "string",
                      "message": "string",
                      "reasons": [
                        "STORE_NOT_FOUND"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "postPickupPoints",
        "x-stoplight": {
          "id": "r11nhbmwivi5m"
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "oneOf": [
                  {
                    "$ref": "#/components/schemas/postPickupPointsWithPostalCode",
                    "x-stoplight": {
                      "id": "f88br9lbudqei"
                    }
                  },
                  {
                    "$ref": "#/components/schemas/postPickupPointsWithGeoPoint",
                    "x-stoplight": {
                      "id": "m6evyswc471ja"
                    }
                  }
                ]
              },
              "examples": {}
            }
          },
          "description": " The method works like a search engine based on mandatory criteria, two options :\n 1) with latitude and Longitude\n 2) with postalCode"
        },
        "description": "This method retrieves the list of relay-point for all the carriers associed to your account.\n\nSearch options enable you to refine the method's eligibility engine. The more options there are, the more precise the results will be.\n\nYou can search for a relay-point based on the contents of the customer basket (parcel dimensions: length, width, height and weight). This allows you to suggest delivery points capable of receiving parcels of a certain weight."
      }
    }
  },
  "components": {
    "schemas": {
      "postPickupPointsWithPostalCode": {
        "type": "object",
        "x-stoplight": {
          "id": "934aa6c06099e"
        },
        "x-examples": {
          "Example 1": {
            "OperatorCode": "string",
            "latitude": 0,
            "longitude": 0,
            "postalCode": 0,
            "limit": 0,
            "offset": 0,
            "kilometricDistance": 0,
            "depositDate": 0,
            "countryCode": "string",
            "accessibility": "string",
            "boxCategoryAccessibility": "string",
            "storeID": 0,
            "type": 0,
            "category": 0,
            "packages": {
              "references": [
                {
                  "reference": "Package_Reference_001",
                  "barcode": {
                    "value": "54fd56g4f5gfd456sd",
                    "type": "barcode",
                    "format": "128"
                  }
                }
              ],
              "length": {
                "value": 10,
                "unit": "cm"
              },
              "width": {
                "value": 10,
                "unit": "cm"
              },
              "height": {
                "value": 10,
                "unit": "cm"
              },
              "weight": {
                "value": 5,
                "unit": "kg"
              },
              "products": [
                {
                  "type": "TYPOLOGY_GENERIC",
                  "ean": "Ean_001",
                  "cug": "Cug_001",
                  "label": "Product_Label",
                  "quantity": 1
                }
              ],
              "quantity": 1,
              "attributes": {
                "footprint": {
                  "value": 10,
                  "unit": "m2"
                }
              },
              "type": "PACKAGE"
            }
          }
        },
        "description": "Specifies the information for a relay point search with postalCode",
        "title": "Search relay point with postalCode",
        "required": [
          "postalCode",
          "packages"
        ],
        "properties": {
          "OperatorCode": {
            "type": "string",
            "example": "Quadient",
            "description": "operatorCode filter = locker manager"
          },
          "postalCode": {
            "type": "number",
            "description": "PostalCode of the search point"
          },
          "limit": {
            "type": "number",
            "description": "Number of pickup points",
            "default": 25,
            "maximum": 100
          },
          "offset": {
            "type": "number",
            "description": "offset to display the pickup points",
            "default": 0
          },
          "kilometricDistance": {
            "type": "number",
            "description": "Distance in kilometres from the search radius",
            "default": 5,
            "maximum": 50
          },
          "depositDate": {
            "type": "string",
            "description": "Estimated drop-off date at the relay point ",
            "format": "date"
          },
          "countryCode": {
            "type": "string",
            "description": "Country code (ISO 3166 alpha-2). View list : [Country code.md]"
          },
          "accessibility": {
            "enum": [
              "ACCESSIBLE"
            ],
            "description": "Pick-Up point Accessibility"
          },
          "boxCategoryAccessibility": {
            "enum": [
              "UPPER",
              "LOWER"
            ],
            "description": "Box Category Accessibility\n\n"
          },
          "packages": {
            "type": "array",
            "description": "All packages\n\n",
            "items": {
              "$ref": "../models/Package/package.json",
              "x-stoplight": {
                "id": "tmev8zj3ui14z"
              }
            }
          }
        },
        "examples": [
          {
            "OperatorCode": "Quadient",
            "postalCode": 0,
            "limit": 25,
            "offset": 0,
            "kilometricDistance": 5,
            "depositDate": "2019-08-24",
            "countryCode": "string",
            "accessibility": "ACCESSIBLE",
            "boxCategoryAccessibility": "UPPER",
            "packages": [
              {
                "references": [
                  {
                    "reference": "Package_Reference_001",
                    "barcode": {
                      "value": "54fd56g4f5gfd456sd",
                      "type": "barcode",
                      "format": "128"
                    }
                  }
                ],
                "length": {
                  "value": 10,
                  "unit": "cm"
                },
                "width": {
                  "value": 10,
                  "unit": "cm"
                },
                "height": {
                  "value": 10,
                  "unit": "cm"
                },
                "weight": {
                  "value": 5,
                  "unit": "kg"
                },
                "products": [
                  {
                    "type": "TYPOLOGY_GENERIC",
                    "ean": "Ean_001",
                    "cug": "Cug_001",
                    "label": "Product_Label",
                    "quantity": 1
                  }
                ],
                "quantity": 1,
                "attributes": {
                  "footprint": {
                    "value": 10,
                    "unit": "m2"
                  }
                },
                "type": "PACKAGE"
              }
            ]
          }
        ]
      },
      "postPickupPointsWithGeoPoint": {
        "type": "object",
        "x-stoplight": {
          "id": "z5jpttrcsofrj"
        },
        "x-examples": {
          "Example 1": {
            "OperatorCode": "string",
            "latitude": 0,
            "longitude": 0,
            "postalCode": 0,
            "limit": 0,
            "offset": 0,
            "kilometricDistance": 0,
            "depositDate": 0,
            "countryCode": "string",
            "accessibility": "string",
            "boxCategoryAccessibility": "string",
            "storeID": 0,
            "type": 0,
            "category": 0,
            "packages": {
              "references": [
                {
                  "reference": "Package_Reference_001",
                  "barcode": {
                    "value": "54fd56g4f5gfd456sd",
                    "type": "barcode",
                    "format": "128"
                  }
                }
              ],
              "length": {
                "value": 10,
                "unit": "cm"
              },
              "width": {
                "value": 10,
                "unit": "cm"
              },
              "height": {
                "value": 10,
                "unit": "cm"
              },
              "weight": {
                "value": 5,
                "unit": "kg"
              },
              "products": [
                {
                  "type": "TYPOLOGY_GENERIC",
                  "ean": "Ean_001",
                  "cug": "Cug_001",
                  "label": "Product_Label",
                  "quantity": 1
                }
              ],
              "quantity": 1,
              "attributes": {
                "footprint": {
                  "value": 10,
                  "unit": "m2"
                }
              },
              "type": "PACKAGE"
            }
          }
        },
        "description": "Specifies the information for a relay point search with latitude and longitude ",
        "title": "Search relay point with latitude and longitude",
        "required": [
          "latitude",
          "longitude",
          "packages"
        ],
        "properties": {
          "OperatorCode": {
            "type": "string",
            "example": "quadient",
            "description": "operatorCode filter = locker manager"
          },
          "latitude": {
            "type": "number",
            "description": "Latitude of the search point"
          },
          "longitude": {
            "type": "number",
            "description": "Longitude of the search point"
          },
          "limit": {
            "type": "number",
            "description": "Number of pickup points",
            "default": 25,
            "maximum": 100
          },
          "offset": {
            "type": "number",
            "description": "offset to display the pickup points",
            "default": 0
          },
          "kilometricDistance": {
            "type": "number",
            "description": "Distance in kilometres from the search radius",
            "default": 5,
            "maximum": 50
          },
          "depositDate": {
            "type": "string",
            "description": "Estimated drop-off date at the relay point ",
            "format": "date"
          },
          "countryCode": {
            "type": "string",
            "description": "Country code (ISO 3166 alpha-2). View list : [Country code.md]"
          },
          "accessibility": {
            "enum": [
              "ACCESSIBLE"
            ],
            "description": "Pick-Up point Accessibility"
          },
          "boxCategoryAccessibility": {
            "enum": [
              "UPPER",
              "LOWER"
            ],
            "description": "Box Category Accessibility\n\n"
          },
          "packages": {
            "type": "array",
            "description": "All packages\n\n",
            "items": {
              "$ref": "../models/Package/package.json",
              "x-stoplight": {
                "id": "1v43w36bur2c3"
              }
            }
          }
        },
        "examples": [
          {
            "OperatorCode": "quadient",
            "latitude": 0,
            "longitude": 0,
            "limit": 25,
            "offset": 0,
            "kilometricDistance": 5,
            "depositDate": "2019-08-24",
            "countryCode": "string",
            "accessibility": "ACCESSIBLE",
            "boxCategoryAccessibility": "UPPER",
            "packages": [
              {
                "references": [
                  {
                    "reference": "Package_Reference_001",
                    "barcode": {
                      "value": "54fd56g4f5gfd456sd",
                      "type": "barcode",
                      "format": "128"
                    }
                  }
                ],
                "length": {
                  "value": 10,
                  "unit": "cm"
                },
                "width": {
                  "value": 10,
                  "unit": "cm"
                },
                "height": {
                  "value": 10,
                  "unit": "cm"
                },
                "weight": {
                  "value": 5,
                  "unit": "kg"
                },
                "products": [
                  {
                    "type": "TYPOLOGY_GENERIC",
                    "ean": "Ean_001",
                    "cug": "Cug_001",
                    "label": "Product_Label",
                    "quantity": 1
                  }
                ],
                "quantity": 1,
                "attributes": {
                  "footprint": {
                    "value": 10,
                    "unit": "m2"
                  }
                },
                "type": "PACKAGE"
              }
            ]
          }
        ]
      },
      "errorCodeResponse": {
        "title": "Error code (errorCode)",
        "x-stoplight": {
          "id": "ktlt9dcqtqto0"
        },
        "type": "object",
        "description": "Corresponds to the model returned in the event of an API error.",
        "examples": [
          {
            "statusCode": 0,
            "error": "string",
            "message": "string",
            "reasons": "string"
          }
        ],
        "properties": {
          "statusCode": {
            "type": "integer",
            "x-stoplight": {
              "id": "q7yz897mknw26"
            },
            "description": "HTTP Status Code"
          },
          "error": {
            "type": "string",
            "x-stoplight": {
              "id": "llxf10hz2g5dp"
            },
            "description": "Title of the error returned"
          },
          "message": {
            "type": "string",
            "x-stoplight": {
              "id": "3oy9wo020oh5i"
            },
            "description": "Description of the error message"
          },
          "reasons": {
            "type": "array",
            "x-stoplight": {
              "id": "p551ohgr7216s"
            },
            "description": "List of possible technical reasons",
            "items": {
              "x-stoplight": {
                "id": "7ilihv4picvke"
              },
              "enum": [
                "STORE_NOT_FOUND",
                "EXCHANGE_PLACE_NOT_FOUND",
                "PICKUP_POINT_NOT_FOUND"
              ]
            }
          }
        }
      }
    },
    "securitySchemes": {
      "API Key - 1": {
        "type": "oauth2"
      }
    },
    "responses": {
      "postPickupPoints": {
        "description": "OK. Contains the retrieved relay points.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "x-examples": {
                "Example 1": {
                  "id": "Auto Spider - Non accessible PMR",
                  "coordinates": {
                    "longitude": 3.06977,
                    "latitude": 50.653697
                  },
                  "address": {
                    "title": "Auto Spider - Non accessible PMR",
                    "addressLine1": "16 RUE DU PRESIDENT POMPIDOU",
                    "addressLine2": "3631",
                    "country": "FR",
                    "postalCode": "59110",
                    "city": "LA MADELEINE"
                  },
                  "openingHours": {
                    "sunday": [],
                    "saturday": [
                      {
                        "start": "12:00",
                        "end": "18:00"
                      }
                    ],
                    "friday": [
                      {
                        "start": "08:30",
                        "end": "14:00"
                      },
                      {
                        "start": "17:00",
                        "end": "20:00"
                      }
                    ],
                    "thursday": [
                      {
                        "start": "08:30",
                        "end": "14:00"
                      },
                      {
                        "start": "17:00",
                        "end": "20:00"
                      }
                    ],
                    "wednesday": [
                      {
                        "start": "08:30",
                        "end": "18:00"
                      }
                    ],
                    "tuesday": [
                      {
                        "start": "08:30",
                        "end": "14:00"
                      },
                      {
                        "start": "17:00",
                        "end": "20:00"
                      }
                    ],
                    "monday": [
                      {
                        "start": "08:30",
                        "end": "14:00"
                      },
                      {
                        "start": "17:00",
                        "end": "20:00"
                      }
                    ]
                  },
                  "closingDates": [],
                  "packageMaxWeight": {
                    "value": 20,
                    "unit": "kg"
                  },
                  "packageMaxDimension": {
                    "value": 200,
                    "unit": "cm"
                  },
                  "packageMaxCombinedLength": {
                    "value": 300,
                    "unit": "cm"
                  },
                  "packageMaxGirth": {
                    "value": 400,
                    "unit": "cm"
                  },
                  "maxPackageQuantity": 1,
                  "carrier": {
                    "code": "qomod",
                    "name": "QOMOD"
                  },
                  "boxCategories": [
                    {
                      "id": "00131",
                      "code": "S",
                      "accessibility": "UPPER"
                    },
                    {
                      "id": "00132",
                      "code": "S",
                      "accessibility": "LOWER"
                    },
                    {
                      "id": "00133",
                      "code": "L"
                    },
                    {
                      "id": "00134",
                      "code": "L",
                      "accessibility": "LOWER"
                    }
                  ],
                  "type": "PICKUP_POINT_RELAY_WITH_LOCKER"
                }
              },
              "required": [
                "id",
                "coordinates",
                "address",
                "openingHours",
                "packageMaxWeight",
                "packageMaxDimension",
                "packageMaxCombinedLength",
                "packageMaxGirth",
                "maxPackageQuantity",
                "carrier",
                "type"
              ],
              "properties": {
                "id": {
                  "type": "string",
                  "description": "ID of the relay point"
                },
                "coordinates": {
                  "$ref": "../models/Location/coordinates.json",
                  "description": "Coordinates of the relay point"
                },
                "address": {
                  "$ref": "../models/Location/address.json",
                  "description": "Full address of the relay point"
                },
                "openingHours": {
                  "type": "object",
                  "description": "Opening hours of the relay point",
                  "properties": {
                    "sunday": {
                      "type": "array",
                      "items": {
                        "$ref": "../models/Common/interval_hour.json"
                      }
                    },
                    "saturday": {
                      "type": "array",
                      "items": {
                        "$ref": "../models/Common/interval_hour.json"
                      }
                    },
                    "friday": {
                      "type": "array",
                      "items": {
                        "$ref": "../models/Common/interval_hour.json"
                      }
                    },
                    "thursday": {
                      "type": "array",
                      "items": {
                        "$ref": "../models/Common/interval_hour.json"
                      }
                    },
                    "wednesday": {
                      "type": "array",
                      "items": {
                        "$ref": "../models/Common/interval_hour.json"
                      }
                    },
                    "tuesday": {
                      "type": "array",
                      "items": {
                        "$ref": "../models/Common/interval_hour.json"
                      }
                    },
                    "monday": {
                      "type": "array",
                      "items": {
                        "$ref": "../models/Common/interval_hour.json"
                      }
                    }
                  }
                },
                "closingDates": {
                  "type": "array",
                  "description": "List of temporary closure dates of the relay point",
                  "items": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "packageMaxWeight": {
                  "$ref": "../models/Dimension/weight.json"
                },
                "packageMaxDimension": {
                  "$ref": "../models/Dimension/length.json"
                },
                "packageMaxCombinedLength": {
                  "$ref": "../models/Dimension/length.json"
                },
                "packageMaxGirth": {
                  "$ref": "../models/Dimension/length.json"
                },
                "maxPackageQuantity": {
                  "type": "integer"
                },
                "carrier": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    }
                  }
                },
                "boxCategories": {
                  "$ref": "../models/PickUpPoint/boxCategory.json"
                },
                "type": {
                  "type": "string",
                  "example": "PICKUP_POINT_RELAY_WITH_LOCKER"
                }
              }
            },
            "examples": {
              "Example 1": {
                "value": {
                  "id": "string",
                  "coordinates": {
                    "latitude": 50.633333,
                    "longitude": 3.066667
                  },
                  "address": {
                    "addressLine1": "string",
                    "addressLine2": "string",
                    "elevator": true,
                    "floor": 0,
                    "doorCode": "string",
                    "postalCode": "string",
                    "city": "string",
                    "district": "string",
                    "country": "string",
                    "comment": "string"
                  },
                  "openingHours": {
                    "sunday": [
                      {
                        "start": "14:15:22Z",
                        "end": "14:15:22Z"
                      }
                    ],
                    "saturday": [
                      {
                        "start": "14:15:22Z",
                        "end": "14:15:22Z"
                      }
                    ],
                    "friday": [
                      {
                        "start": "14:15:22Z",
                        "end": "14:15:22Z"
                      }
                    ],
                    "thursday": [
                      {
                        "start": "14:15:22Z",
                        "end": "14:15:22Z"
                      }
                    ],
                    "wednesday": [
                      {
                        "start": "14:15:22Z",
                        "end": "14:15:22Z"
                      }
                    ],
                    "tuesday": [
                      {
                        "start": "14:15:22Z",
                        "end": "14:15:22Z"
                      }
                    ],
                    "monday": [
                      {
                        "start": "14:15:22Z",
                        "end": "14:15:22Z"
                      }
                    ]
                  },
                  "closingDates": [
                    "2019-08-24"
                  ],
                  "packageMaxWeight": {
                    "value": 5,
                    "unit": "kg"
                  },
                  "packageMaxDimension": {
                    "value": 10,
                    "unit": "cm"
                  },
                  "packageMaxCombinedLength": {
                    "value": 10,
                    "unit": "cm"
                  },
                  "packageMaxGirth": {
                    "value": 10,
                    "unit": "cm"
                  },
                  "maxPackageQuantity": 0,
                  "carrier": {
                    "code": "string",
                    "name": "string"
                  },
                  "boxCategories": {
                    "id": "BoxCategory_001",
                    "code": "S",
                    "accessibility": "UPPER"
                  },
                  "type": "PICKUP_POINT_RELAY_WITH_LOCKER"
                }
              }
            }
          }
        }
      },
      "errorCodeResponse": {
        "description": ""
      }
    }
  }
}